import './globals.css'
import type { Metadata } from 'next'
import clsx from 'clsx'
import { Montserrat } from 'next/font/google'
import Footer from '@/components/comon/Footer'
import Header from '@/components/comon/Header'
import { MediaQueryProvider } from '@/contexts/MediaQueryContext'
import ScrollTop from '@/components/ScrollTop'

import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import 'swiper/css/grid';
import 'swiper/css/thumbs'
import 'swiper/css/free-mode'

import 'react-loading-skeleton/dist/skeleton.css'

const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-mont'
})

export const metadata: Metadata = {
    title: 'Truyện Hay ',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <html lang="en">
            <body
                className={clsx(montserrat.variable, 'font-mont bg-light w-full font-normal')}
                cz-shortcut-listen="true"
            >
                <MediaQueryProvider >
                    <Header />
                    {children}
                    <Footer />
                    <ScrollTop />
                </MediaQueryProvider>
            </body>
        </html>
    )
}
